version: '3'

services:

  server:
    build: ./server/
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - '3001:3001'

  client:
    build: ./client/
    environment:
      APP_SERVER_PORT: ${REACT_APP_PORT}
    ports:
      - '3000:3000'
    links: 
      - server